### ISSUE TITLE
Remove writelns from test file

### ISSUE THREAD

**Issue by buddha314** [Deep6AI/epoch#22]
The tests should be as quiet and quick as possible, there to make sure everything is running. Also, with Charcoal you can now do

```
proc testTestes() {
  var t= this.setUp("Testes");
  // do stuff
  this.tearDown(t)
}
```

And you will get a timing message at the end.

**Comment by Tshimanga** [comment]
Yeah, now that I've moved the examples out into their own folder I can dedicate EpochTest.chpl to strict unit testing.

**Comment by Tshimanga** [comment]
Done.
