### ISSUE TITLE
I predict .predict() will fail

### ISSUE THREAD

**Issue by buddha314** [Deep6AI/epoch#28]
Seems like there is no `.predict()` method.  Ah, but who needs it?  I imagine a future scenario where someone will want to imagine a future scenario.  Can you?  NO!  You can't because there is NO PREDICT METHOD!! ;)

**Comment by Tshimanga** [comment]
Well, there was always a predict method. Just wasn't called predict. But now there is a method called predict that just refers to the original predict so

Closed.
