### ISSUE TITLE
No victory for vectors

### ISSUE THREAD

**Issue by buddha314** [Deep6AI/epoch#29]
It appears the `.forwardPass()` routine fails on vectors, need 2D arrays.  Should be able to put in a catch for `if X.shape.size ==1` or something like that.

**Comment by Tshimanga** [comment]
Hmm must be a type issue. I have been using rank 1 matrices freely but I have been using the `Vector` class. Is there a benefit to using the `Vector` class or can everything just be a matrix?

For example(s), the approximators all take 1 by n  vectors to train/predict with.

**Comment by Tshimanga** [comment]
Closed: Unable to reproduce.
