### ISSUE TITLE
Loss can lose its dim

### ISSUE THREAD

**Issue by buddha314** [Deep6AI/epoch#33]
I'm not sure what makes this happen, but in the `Loss` function for `linear` at least, `Y` and `A` may be 1D or 2D.  I've run into this around line 450 of `Neural.chpl`

```
Epoch J Y.domain {1..99}
Epoch J A.domain {1..1, 1..99}
/home/buddha/git/epoch/src/Neural.chpl:452: error: zippered iterations have non-equal lengths
Makefile:12: recipe for target 'run' failed
make: *** [run] Error 1
```

**Comment by Tshimanga** [comment]
This arose out of a failed attempt to violate type safety. Outputs `A` from the neural networks are always rank 2 arrays so as to accommodate outputs of arbitrary dimension. Since Chapel is a language that cares about type consistency, you have to define your `Y`s to be rank 2 arrays as well.
